# Generated by Django 4.2 on 2025-07-21 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Useruser',
        ),
    ]
